allowed-duplicate-crates = [
    "thiserror",
    "thiserror-impl",
    "gloo-net",
    "syn",
    "getrandom",
    "webpki-roots",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "rand",
    "rand_chacha",
    "rand_core",
    "foldhash",
    "windows-sys",
]
