[book]
title = "Revaer Documentation"
authors = ["Revaer Contributors"]
language = "en"
src = "docs"

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
copy-fonts = true
no-section-label = true
git-repository-url = "https://github.com/VannaDii/revaer"
additional-js = ["scripts/mermaid.min.js", "scripts/mermaid-init.js"]

[output.html.search]
enable = true
limit-results = 30

[preprocessor.mermaid]
command = "mdbook-mermaid"
